# Makefile for TPos midlet

# Project name
PRNAME=TPos
# Entry class
ECLASS=TPos
# Object list
OBJS=TPos.class TPosForm.class
# Basename for .jar, .jad
PRBNAME=tpos
# Description
DESC=A simple midlet for testing form entry in the self-moving boards
MIDLET_URL=http://www.pspkvm.org
MIDLET_AUTHOR=feedback@pspkvm.org
MIDLET_VERSION=1.1.0

# Std Makefile include
include ../top.inc
