# Makefile for Sound Out midlet

# Project name
PRNAME=NoteMidlet
# Entry class
ECLASS=NoteMidlet
# Object list
OBJS=NoteMidlet.class
# Basename for .jar, .jad
PRBNAME=notemidlet
# Description
DESC=A simple text editor midlet

# Std Makefile include
include ../top.inc
