# Makefile for Sound Out midlet

# Project name
PRNAME=DZTest
# Entry class
ECLASS=DZTest
# Object list
OBJS=DZTest.class DZTestCanvas.class
# Basename for .jar, .jad
PRBNAME=dztest
# Description
DESC=A simple midlet testing the drawing code for the Danzeff clone
MIDLET_URL=http://www.pspkvm.org
MIDLET_AUTHOR=feedback@pspkvm.org
MIDLET_VERSION=1.1.0

# Std Makefile include
include ../top.inc
