# Makefile for HelloWorld midlet

# Project name
PRNAME=Hello World
# Entry class
ECLASS=HelloWorld
# Object list
OBJS=HelloWorld.class
# Basename for .jar, .jad
PRBNAME=hello
# Description
DESC=Yer standard Hello World, in midlet form
MIDLET_URL=http://pspkvm.org
MIDLET_AUTHOR=feedback@pspkvm.org
MIDLET_VERSION=1.1.0

# Std Makefile include
include ../top.inc
