# Makefile for HelloWorld midlet

# Project name
PRNAME=Hello World
# Entry class
ECLASS=HelloWorld
# Object list
OBJS=HelloWorld.class
# Basename for .jar, .jad
PRBNAME=hello
# Description
DESC=Yer standard Hello World, in midlet form

# Std Makefile include
include ../top.inc
