# Makefile for Sound Out midlet

# Project name
PRNAME=NoteMidlet
# Entry class
ECLASS=NoteMidlet
# Object list
OBJS=NoteMidlet.class
# Basename for .jar, .jad
PRBNAME=notemidlet
# Description
DESC=A simple text editor midlet
# URL, vendor, version
MIDLET_URL=http://www.pspkvm.org
MIDLET_AUTHOR=feedback@pspkvm.org
MIDLET_VERSION=1.1.0

# Std Makefile include
include ../top.inc
